// Post-build: give the panel bundle a content-hashed filename, hash the card
// separately, and write both into the Python package so the integration, the
// filenames and the hashes can never disagree (FRONTEND.md §1.4).
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const pkgDir = join(root, "python", "anycubic_cloud_frontend");
const pkgDist = join(pkgDir, "dist");

const WEBCOMPONENT = "anycubic-cloud-panel";
const CARD = "anycubic-card.js";

const hash8 = (file) => createHash("sha256").update(readFileSync(file)).digest("hex").slice(0, 8);

// Drop panel files from earlier builds, keep the fresh unhashed one.
for (const name of readdirSync(dist)) {
  if (/^entrypoint\.[0-9a-f]{8}\.js$/.test(name)) rmSync(join(dist, name));
}
const panelHash = hash8(join(dist, "entrypoint.js"));
const cardHash = hash8(join(dist, CARD));
const entrypoint = `entrypoint.${panelHash}.js`;
renameSync(join(dist, "entrypoint.js"), join(dist, entrypoint));

const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;
const info = { version, webcomponent: WEBCOMPONENT, entrypoint, card: CARD, panel_hash: panelHash, card_hash: cardHash };
writeFileSync(join(dist, "build.json"), `${JSON.stringify(info, null, 2)}\n`);

rmSync(pkgDist, { recursive: true, force: true });
mkdirSync(pkgDist, { recursive: true });
for (const name of [entrypoint, CARD, "build.json"]) copyFileSync(join(dist, name), join(pkgDist, name));

writeFileSync(
  join(pkgDir, "_build.py"),
  `"""Generated by scripts/stamp.mjs at build time. Do not edit."""\n\n` +
    `FRONTEND_VERSION = ${JSON.stringify(version)}\n` +
    `ENTRYPOINT_JS = ${JSON.stringify(entrypoint)}\n` +
    `PANEL_HASH = ${JSON.stringify(panelHash)}\n` +
    `CARD_JS = ${JSON.stringify(CARD)}\n` +
    `CARD_HASH = ${JSON.stringify(cardHash)}\n`,
);

console.log(`panel ${entrypoint}, card ${CARD}?v=${cardHash}`);
